name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Default to least privilege; individual jobs can elevate if needed.
permissions:
  contents: read

# Avoid duplicate runs when a PR is force-pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    name: terraform fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: "1.9.5"
      - name: terraform fmt -check -recursive
        run: terraform fmt -check -recursive

  validate:
    name: terraform validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - modules/baseline
          - examples/minimal
          - examples/with-existing-cloudtrail
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: "1.9.5"
      - name: terraform init (no backend)
        working-directory: ${{ matrix.path }}
        run: terraform init -backend=false
      - name: terraform validate
        working-directory: ${{ matrix.path }}
        run: terraform validate

  tflint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4
        with:
          tflint_version: latest
      - name: tflint init
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: tflint
        run: tflint --recursive --format compact

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6 # v1.0.3
        with:
          working_directory: modules/baseline
          soft_fail: false
