name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  fmt:
    name: terraform fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
      - name: terraform fmt -check -recursive
        run: terraform fmt -check -recursive

  validate:
    name: terraform validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - modules/baseline
          - examples/minimal
          - examples/with-existing-cloudtrail
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
      - name: terraform init (no backend)
        working-directory: ${{ matrix.path }}
        run: terraform init -backend=false
      - name: terraform validate
        working-directory: ${{ matrix.path }}
        run: terraform validate

  tflint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - name: tflint init
        run: tflint --init
      - name: tflint
        run: tflint --recursive --format compact

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: modules/baseline
          soft_fail: false
